# Generated by Django 6.0.1 on 2026-01-10 22:25

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historique_title_fr', models.CharField(max_length=255, verbose_name='Titre Historique (FR)')),
                ('historique_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='History Title (EN)')),
                ('historique_description_fr', models.TextField(verbose_name='Description Historique (FR)')),
                ('historique_description_en', models.TextField(blank=True, null=True, verbose_name='History Description (EN)')),
                ('historique_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Historique Image')),
                ('vision_title_fr', models.CharField(max_length=255)),
                ('vision_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('vision_description_fr', models.TextField()),
                ('vision_description_en', models.TextField(blank=True, null=True)),
                ('vision_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Vision Image')),
                ('organisation_title_fr', models.CharField(max_length=255)),
                ('organisation_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_description_fr', models.TextField()),
                ('organisation_description_en', models.TextField(blank=True, null=True)),
                ('organisation_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Organisation Image')),
                ('direction_title_fr', models.CharField(max_length=255)),
                ('direction_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_message_fr', models.TextField()),
                ('direction_message_en', models.TextField(blank=True, null=True)),
                ('direction_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Direction Image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'ordering': ['-created_at'],
            },
        ),
    ]
