# Generated by Django 6.0.1 on 2026-01-11 00:42

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position_fr', models.CharField(max_length=255, verbose_name='Poste (FR)')),
                ('position_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position (EN)')),
                ('bio_fr', models.TextField(blank=True, null=True, verbose_name='Biographie (FR)')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Biography (EN)')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'ordering': ['full_name'],
            },
        ),
    ]
