# Generated by Django 6.0.1 on 2026-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipemember',
            options={'ordering': ['created_at'], 'verbose_name': "Membre d'équipe", 'verbose_name_plural': "Membres d'équipe"},
        ),
        migrations.AddField(
            model_name='equipemember',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Coché si membre dirigeant'),
        ),
        migrations.AddField(
            model_name='equipemember',
            name='role',
            field=models.CharField(choices=[('dirigeant', 'Dirigeant'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
    ]
