# Generated by Django 6.0.1 on 2026-01-11 15:07

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_equipemember_options_equipemember_is_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('cover_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Photo')),
                ('image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 1')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 2')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 3')),
                ('image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 4')),
                ('image_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 5')),
                ('image_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 6')),
                ('image_7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 7')),
                ('image_8', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 8')),
                ('image_9', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 9')),
                ('image_10', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 10')),
                ('image_11', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 11')),
                ('image_12', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 12')),
                ('image_13', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 13')),
                ('image_14', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 14')),
                ('image_15', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 15')),
                ('image_16', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 16')),
                ('image_17', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 17')),
                ('image_18', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 18')),
                ('image_19', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 19')),
                ('image_20', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 20')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
