# Generated by Django 6.0.1 on 2026-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title_fr',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, choices=[('selected_projects', 'Selected Projects'), ('adaptive_transformation', 'Adaptive Transformation'), ('advisory_services', 'Advisory Services'), ('aviation', 'Aviation'), ('branded_environments', 'Branded Environments'), ('corporate_commercial', 'Corporate and Commercial'), ('cultural_civic', 'Cultural and Civic'), ('federal', 'Federal'), ('health', 'Health'), ('health_education', 'Health Education'), ('higher_education', 'Higher Education'), ('hospitality', 'Hospitality'), ('k12_education', 'K-12 Education'), ('landscape_architecture', 'Landscape Architecture'), ('residential', 'Residential'), ('science_technology', 'Science and Technology'), ('sports_entertainment', 'Sports, Recreation, and Entertainment'), ('transportation', 'Transportation'), ('urban_design', 'Urban Design'), ('workplace', 'Workplace')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='completion_date_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='completion_date_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='surface_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='surface_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
