# Generated by Django 6.0.1 on 2026-01-13 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_portfolio_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Photo'),
        ),
    ]
