# Generated by Django 6.0.1 on 2026-01-25 19:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_portfolio_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipemember',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Image'),
        ),
    ]
